// problemTypes.ts
export const problemTypes = [
    { label: "DP", value: "dp" },
    { label: "그리디", value: "greedy" },
    { label: "백트래킹", value: "backtracking" },
    { label: "투포인터", value: "two-pointers" },
    { label: "누적합", value: "prefix-sum" },
    { label: "최단경로", value: "dijkstra" },
    { label: "위상정렬", value: "topological-sort" },
    { label: "BFS", value: "bfs" },
    { label: "DFS", value: "dfs" },
    { label: "트리", value: "tree-basic" },
    { label: "정렬", value: "sorting" },
    { label: "탐색", value: "searching" },
    { label: "해시", value: "hash-map" },
    { label: "스택/큐", value: "stack-queue-deque" },
    { label: "문자열", value: "string-basic" },
    { label: "배열", value: "array" },
    { label: "기타", value: "ect" },
  ]